name: Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Deploy to Neocities
        env:
          NEOCITIES_API_TOKEN: ${{ secrets.NEOCITIES_API_TOKEN }}
        run: |
          echo "Deploying site to Neocities..."
          # Loop through all files and upload
          find . -type f ! -name '.git*' ! -name 'neocities.yaml' | while read file; do
            echo "Uploading $file"
            curl -s -X POST -u "$NEOCITIES_API_TOKEN:" \
              -F "file=@$file" \
              https://neocities.org/api/upload
          done
          echo "Deployment complete."
